### ISSUE TITLE
error on line 63 in install.sh

### ISSUE THREAD

**Issue by ihs103** [sunbeam-labs/sunbeam#135]
What is in line 63 and how can I fix this error?

> Irmgards-iMac:sunbeam-stable Irmgard$ git clone -b stable https://github.com/sunbeam-labs/sunbeam sunbeam-stable
> Cloning into 'sunbeam-stable'...
> remote: Counting objects: 2034, done.
> remote: Compressing objects: 100% (91/91), done.
> remote: Total 2034 (delta 77), reused 133 (delta 67), pack-reused 1869
> Receiving objects: 100% (2034/2034), 1.08 MiB | 0 bytes/s, done.
> Resolving deltas: 100% (1143/1143), done.
> Checking connectivity... done.
> Irmgards-iMac:sunbeam-stable Irmgard$     cd sunbeam-stable
> Irmgards-iMac:sunbeam-stable Irmgard$     ./install.sh
> readlink: illegal option -- f
> usage: readlink [-n] [file ...]
> 2018-04-30 21:04:56 UTC [    error] Error in /Users/Irmgard/sunbeam-stable/sunbeam-stable/install.sh in function . on line 63
> Irmgards-iMac:sunbeam-stable Irmgard$     tests/run_tests.bash -e sunbeam
> Running setup... 
> Failed command error output:
> usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
>        mktemp [-d] [-q] [-u] -t prefix 
> x (log: setup.[out/err])
> -- TESTS FAILED --
>

**Comment by eclarke** [comment]
Hi there,

It looks like the error is because you're running on a Mac, which we don't currently support (Sunbeam uses a lot of Linux-specific shell commands). If you have access to a Linux server, I'd use that, or download and install a Linux virtual machine- [Vagrant](http://vagrantup.com) is a pretty easy way to get a Linux virtual machine up and running.

I'll add information to the install guide to specify the Linux requirement.

Let me know if I can be any more help.

**Comment by eclarke** [comment]
Upon inspection I see that we said it worked on Macs multiple times, so my apologies for that!
