### ISSUE TITLE
Two missing requirements

### ISSUE THREAD

**Issue by kevinmcc21** [sunbeam-labs/sunbeam#145]
Sunbeam installation "worked" for me without issue, but attempting to run sunbeam init gave two errors, both missing packages:
semantic_version
ruamel_yaml
A quick pip install fixed both issues and it seems to work now.  (Apologies, I already lost the error message, so i can't provide exact text...)

**Comment by eclarke** [comment]
Weird... can you give me more details of your setup? We have both of those packages specified in the `environment.yml` file and our integration tests run `sunbeam init` during routine testing, so I'm not sure where this problem is coming from. In particular, did you already have conda installed, and what version is it?

**Comment by kevinmcc21** [comment]
I did have conda installed previously, yes.  Version 4.2.9.

**Comment by eclarke** [comment]
Was it miniconda2 or miniconda3?

**Comment by ressy** [comment]
Closing this one because we eventually realized that that install hadn't completed with all packages installed after all, and that probably explains the missing packages here.
