### ISSUE TITLE
Using *.smk file endings instead of *.rules

### ISSUE THREAD

**Issue by acesnik** [sunbeam-labs/sunbeam#196]
Hi there,

This is a nicely designed project, and I was looking through it for hints on organizing snakemake projects. 

The *.rules files weren't being highlighted in my IDE, and it looks like *.smk is the file ending that most IDEs use for snakemake. You might consider changing the rules file names to end with *.smk.

https://snakemake.readthedocs.io/en/stable/project_info/faq.html#how-do-i-enable-syntax-highlighting-in-vim-for-snakefiles

Thanks!

Anthony

**Comment by eclarke** [comment]
Good call. It looks like the emacs snakemake-mode works with either so I'd be fine with that. Thanks for the tip!

**Comment by ressy** [comment]
Just realized the Snakemake documentation itself is a little inconsistent on what file extension to use.  The [docs say .smk](https://snakemake.readthedocs.io/en/stable/project_info/faq.html#how-do-i-enable-syntax-highlighting-in-vim-for-snakefiles) but the example vim config they link to [says .snake](https://raw.githubusercontent.com/snakemake/snakemake/master/misc/vim/syntax/snakemake.vim).  Elsewhere online I'm seeing:
 * entries for emacs that use .rules, .smrules, .smk, or .snakefile: https://github.com/kyleam/snakemake-mode/blob/master/snakemake-mode.el
 * entries for vim that use .rules, .snakefile, or .snake: https://github.com/ibab/vim-snakemake/blob/master/ftdetect/snakemake.vim

...unfortunately no single one seems to be in use in all cases.  I'd argue for letting it stay as it is unless/until Snakemake officially settles on one extension and gets the editors and IDEs on-board with it, particularly since we'll need to adjust some of the extension logic to match whatever we'd change it to.  But let me know if you see a ton of projects and/or editors self-organizing around .smk-- even if it's just  de-facto standard, that probably would be worth aligning with.
