### ISSUE TITLE
single molecule sequencing  

### ISSUE THREAD

**Issue by wangjiawen2013** [sunbeam-labs/sunbeam#206]
Dear,
Does sunbeam support data generated from 16S rDNA amplicon sequencing or single molecule sequencing techniques such as Nanopore and BioPacific ?

**Comment by louiejtaylor** [comment]
Thanks for the issue, @wangjiawen2013! Sunbeam runs on .fastq.gz files, so if your data are FASTQ-formatted, the pipeline should run fine. That being said, we designed the pipeline with short-read, shotgun metagenomic sequencing in mind. Thus, it doesn't include many of the processing steps or tools that are standard in 16S analysis (e.g. we don't look for chimeras, or call OTUs) or Oxford Nanopore (we don't do any sort of basecalling or error correction, and the assemblers we use are short-read specific and I'm not sure how they'd perform with long reads).

Short answer: while you could probably run the pipeline without error, we don't recommend it on either of these data types since we haven't designed or tested the pipeline for these scenarios.
