### ISSUE TITLE
test failed with sunbeam test when installing on ubuntu virtual instance

### ISSUE THREAD

**Issue by JulianMarchesi** [sunbeam-labs/sunbeam#207]
followed the instructions from here - https://sunbeam.readthedocs.io/en/latest/quickstart.html

$ tests/run_tests.bash -e sunbeam
Running setup... ✔
Running build_test_data...
Failed command error output:
Guessing sample name format from files in /tmp/tmp.QZ22SLPIpD/data_files...
  Best guess: PCMP_{sample}_R{rp}.fastq.gz
Found 3 samples in /tmp/tmp.QZ22SLPIpD/data_files.
New sample list written to /tmp/tmp.QZ22SLPIpD/samples.csv
New config file written to /tmp/tmp.QZ22SLPIpD/tmp_config.yml
x (log: /tmp/tmp.QZ22SLPIpD/build_test_data.[out/err])
-- TESTS FAILED --

any suggestions?

**Comment by JulianMarchesi** [comment]
any suggestions?

**Comment by louiejtaylor** [comment]
This is weird. Based on the output of the test, it looks like it should have succeeded (or, at least, I can't see any reason why it would've failed). Do you mind attaching the two log files, which should be located here: `/tmp/tmp.QZ22SLPIpD/build_test_data.[out/err]`? Maybe there's something there that'll give us a clue as to what went wrong. Thank you!

**Comment by JulianMarchesi** [comment]
Hi Louise

Here is the out file

~/sunbeam-stable/tests ~/sunbeam-stable
~/sunbeam-stable
/tmp/tmp.QZ22SLPIpD ~/sunbeam-stable
Added "raw/GCF_Bfragilis_10k_genomic.fna" to library (mindb)
Added "raw/GCF_Ecoli_10k_genomic.fna" to library (mindb)
Kraken build set to minimize disk writes.
Creating k-mer set (step 1 of 6)...
Found jellyfish v2.2.7
Kraken requires jellyfish version 1

Here is the err file

Guessing sample name format from files in /tmp/tmp.QZ22SLPIpD/data_files...
  Best guess: PCMP_{sample}_R{rp}.fastq.gz
Found 3 samples in /tmp/tmp.QZ22SLPIpD/data_files.
New sample list written to /tmp/tmp.QZ22SLPIpD/samples.csv
New config file written to /tmp/tmp.QZ22SLPIpD/tmp_config.yml
tests/run_tests.bash: line 159: deactivate: No such file or directory

cheers

Julian

**Comment by ressy** [comment]
> tests/run_tests.bash: line 159: deactivate: No such file or directory

That's odd, since even the newer conda should still allow the `source deactivate` command within an environment (even though it complains about wanting `conda deactivate`).  When run outside any environment I get that same error with the newer conda, though, so possibly the environment install or activation is the problem.

Julian, do you see the sunbeam environment if you run `conda env list`?  Are you able to run `conda activate sunbeam` manually?

**Comment by louiejtaylor** [comment]
So, based on my reading of the log files, it looks like there are two issues here. Neither of which I have seen before.

The first thing I see is kraken yelling about the wrong version of jellyfish. Which is weird, because I'm pretty sure we pin to version 1.1.1 in the [environment.yml](https://github.com/sunbeam-labs/sunbeam/blob/dev/environment.yml). For this particular issue, from within the sunbeam env (enter using `conda activate sunbeam`), would you mind pasting the output from `conda list`? Sunbeam should make its own environment using conda (and there shouldn't be any version issues) so I'm a bit confused as to why you're seeing this.

The second is here:

    tests/run_tests.bash: line 159: deactivate: No such file or directory

This looks like something conda-related, potentially also related to/fixed by [#204](https://github.com/sunbeam-labs/sunbeam/pull/204) (thoughts, @ressy?). Do you know what version of conda you're running?

**Comment by ressy** [comment]
Whoops, Louis and I responded at the same moment.  I think #204 could help simplify the situation but it looks like it *should* still work either way.  Maybe both the deactivate error and jellyfish warning could be related to the environment failing to activate at the start (if there's a jellyfish install in the base environment, that is)?

Just to add into what Louis was asking, what happens with this?

    conda env list
    conda --version
    which jellyfish

**Comment by JulianMarchesi** [comment]
Thanks guys when I get back from hols I will try your suggestions

**Comment by JulianMarchesi** [comment]
Thanks – when I have some spare time I will try again

J


[signature_jrm]
Julian R. Marchesi (pronounced Markhazy)

Professor of Digestive Health, Division of Integrative Systems Medicine and Digestive Disease, Imperial College London, London W2 1NY Tel: +44 (0)20 331 26197

Professor in Human Microbiome Research School of Biosciences, Museum Avenue, Cardiff University, Cardiff, CF10 3AT, Tel: +44 (0)29 208 74188, Fax: +44 (0)29 20874305, Mobile 07885 569144

**Comment by louiejtaylor** [comment]
Hi @JulianMarchesi--I'm going to close this issue for now, but feel free to reopen it if you continue to have problems! Hopefully the updates we've made to the pipeline since you've had this issue will fix any of the problems you were having.
