### ISSUE TITLE
Using Kraken2 instead of Kraken db

### ISSUE THREAD

**Issue by elithess** [sunbeam-labs/sunbeam#208]
Is there a way to swap the older version of kraken with the newer version of it in the pipeline?

**Comment by louiejtaylor** [comment]
Hi @elithess! We don't currently support kraken2 although we are planning to in the next major version of Sunbeam. I know I have some rules from another project for running kraken2--I'll see if they can be easily incorporated into a Sunbeam extension. That would be nice to have until the next major version (and it'd probably make the version transition smoother). I'll get back to you soon!

**Comment by elithess** [comment]
Perfect! Thanks for the prompt response!
Looking forward to it :)

**Comment by louiejtaylor** [comment]
Update: new extension, sbx_kraken2, supports running kraken2 in Sunbeam! Follow the instructions here to install and run the extension: https://github.com/louiejtaylor/sbx_kraken2

@elithess, let me know if you have any issues using it--I've tested with a paired-end dataset (although it should run using either single- or paired-end reads.

For posterity (@ressy)--we should essentially be able to drop the new `kraken2_classify_annotate` rule from the extension in place of the existing `kraken_classify` and `kraken_report` rules when we're ready to move to 3.0. The other ones in the extension (`kraken2_biom` and `classic_k2_biom`), are copy-pasted into the extension from the normal rules, and just re-hooked to output in the `CLASSIFY_FP/kraken2/` dir instead of `CLASSIFY_FP/kraken/` for disambiguation in case the user wants both.

**Comment by elithess** [comment]
Should I remove this from my config file then?

**Comment by louiejtaylor** [comment]
Based on this line:

    /bin/bash: activate: No such file or directory

It looks like something is going weird when snakemake tries to use a separate conda environment with the kraken2 rule. 

A few quick debugging questions:
 - Based on the fact that Sunbeam tried to run the kraken2 rule, I assume that you have already successfully run the QC steps, is that correct?
 - What system are you running this on?
 - I'm curious as to which version of Snakemake/conda you have. Would you mind running `conda --version` and `snakemake -v`? (you should check the snakemake version within the sunbeam env, e.g. after `conda activate sunbeam`)

Thank you!

**Comment by elithess** [comment]
To answer your questions:

- Yes, the QC ran fine. No, issues.
- Ubuntu 18.04.2 LTS
- conda 4.6.14  &   snakemake 4.8.1

Hope this helps!

**Comment by louiejtaylor** [comment]
Great, thanks! I had previously tested it on conda 4.6.12 and snakemake 4.8.1. Trying on 4.6.14 now.

For @ressy:  it looks like multiple users are having issues with conda/subcommands (e.g. [`tests/run_tests.bash: line 159: deactivate: No such file or directory`](https://github.com/sunbeam-labs/sunbeam/issues/207#issuecomment-513843953) from #207 ). I will try to dig into this today--I wonder if this is a symptom of `source activate` support

**Comment by louiejtaylor** [comment]
Weiiird. It ran just fine for me on those versions. I found a [snakemake issue](https://bitbucket.org/snakemake/snakemake/issues/1115/cannot-activate-conda-enironment-using) where some users resolved the problem by downgrading their conda version. If you don't mind having an earlier conda version, you could try that:

    conda install -n base conda=4.5.13

**Comment by elithess** [comment]
After conda downgrading, it ran fine! Thanks for the help!

**Comment by louiejtaylor** [comment]
Great! Glad that worked!

**Comment by ressy** [comment]
Thanks Louis!
