### ISSUE TITLE
Issue with old paired-end illumina sequence identifiers

### ISSUE THREAD

**Issue by khillion** [sunbeam-labs/sunbeam#221]
Hi,

I am not sure this is the right place since the issue is likely to be related with [komplexity](https://github.com/eclarke/komplexity) that seems to only handle newer illumina sequence identifiers when it deals with paired-end data.

I realized that the step in `qc` using `komplexity` did not work if we are processing paired-end data with the "old" illumina sequence identifiers, when you have the information about pair in the name.

Sequences are identified by komplexity by the full identifier of the sequence (including `/1` or `/2`) therefore only identified reads are removed and we end up with different number of reads between your `R1` and `R2` files.

Since I was working on simulated data, I could make a small hack for the moment with a small `sed` but do you think it would be easy to allow `komplexity` to handle this kind of identifier format?

Cheers,
Kenzo

-------

### Illumina sequence identifiers

Old ID | Recent ID
------------ | -------------
READNAME/1 | READNAME 1:N:0:ACT

**Comment by louiejtaylor** [comment]
Thanks for the issue! We should probably handle this. I think this issue arises [here](https://github.com/sunbeam-labs/sunbeam/blob/dev/rules/qc/qc.rules#L182) in the `remove_low_complexity` rule:

    gzip -dc {input.reads} | rbt fastq-filter {input.ids} |\
    gzip > {output}

Basically, we filter by read ID, which using the new method works fine (filter if either or both are low-complexity). But if your read IDs are different between samples, you'll likely end up with unpaired sequences, as you saw. Come to think of it, I wonder if this is also an issue for `filter_reads` in [decontam](https://github.com/sunbeam-labs/sunbeam/blob/dev/rules/qc/decontaminate.rules)?

The options I see for resolving this:
 - Add a config option (`read_id_suffix`?), then have a rule in between `find_low_complexity` and `remove_low_complexity` that generates a version of the '{sample}.filtered_ids' file with all of the read names (also.
 - Add a step immediately after host read removal that runs one of the nice read-pairing tools--this has the advantage of fixing any weird unpaired-ness from the input reads (sometimes happens with SRA downloads). Generally these keep properly reads, and dump unpaired ones into an extra file.
 - Add an early step that fixes the read names--I know there are tools that do this too (some may also do the pairing in the previous step). This has the disadvantage (?) of renaming the user's reads, but I think there might be downstream steps (megahit?) that are broken by non-perfect read name matches. And I think mostly what we'd be removing is the suffix, so there's not really any information lost

Thoughts, @ressy?

**Comment by ressy** [comment]
Yes!  I know I dealt with this exact same problem last year some time and I'm digging through my notes to try to remember what my own fix was at the time.  I think it may have been a trick with sed or similar to just modify the sequence IDs just like @khillion described, but we really should have a method built-in (so thank you for bringing this up).  And yes I think that's just where I had trouble too, where my filtered_ids file going into `remove_low_complexity` had IDs that would only ever be in R1 or R2 instead of general for both.

I like the idea (combo of Louis' first and third I think?) of a config option, disabled by default, that could strip off a suffix from the read IDs early on so your IDs are unified for a given read pair.  That would be fairly simple to do and respectful of the principal of least astonishment, I think, since the modification is clear and controlled by the user.  I like the fact that right now you can trace your individual reads along with their original IDs pretty deep into the pipeline if need be (e.g. peeking into the raw kraken output or the mapping results) and that would basically stay the same even with an ID suffix removal.  On the other hand something to check up on the sanity of the read pairing early on sounds like a good feature to have too, maybe as a separate improvement alongside ID suffix removal?

(Oh and as far as komplexity goes, it uses the read IDs supplied by rust-bio, and rust-bio uses a space as the delimiter that's the de-facto standard to determine a read ID, so whatever IDs are going in are the ones going out for any give file.  That all seems appropriate to me and probably not komplexity's issue to deal with, so I figure Kenzo-Hugo is right to bring this up here, and Sunbeam is the right place to help the user out with that when it comes to paired reads.  @eclarke does that seem about right?)

**Comment by ressy** [comment]
I'm looking at the tests to see how much trouble it'd be to handle this as a new test case and I think we may be able to get away with just appending /1 or /2 to the existing sequence IDs in another instance of the dummy data.

So instead of this for both R1 and R2:

```
@D00728:28:C9W1KANXX:0
@D00728:28:C9W1KANXX:1
@D00728:28:C9W1KANXX:2
@D00728:28:C9W1KANXX:3
...
```

We'll have R1 as:
```
@D00728:28:C9W1KANXX:0/1
@D00728:28:C9W1KANXX:1/1
@D00728:28:C9W1KANXX:2/1
@D00728:28:C9W1KANXX:3/1
...
```
And R2 as:

```
@D00728:28:C9W1KANXX:0/2
@D00728:28:C9W1KANXX:1/2
@D00728:28:C9W1KANXX:2/2
@D00728:28:C9W1KANXX:3/2
...
```

I'll try this out and report back.

**Comment by ressy** [comment]
There we go, test_all still runs fine but test_all_old_illumina fails in align_to_host with the "paired reads have different names" error.

**Comment by ressy** [comment]
How's this?  The QC adapter rules here pull from a new qc/00_samples directory, which contains either symlinks to the original files or ID-modified versions, if you give a config option for it with a regular expression.  It's just a few lines of Biopython to modify the IDs.  Since each config section has a key named "suffix" already for directory names, I used the name "seq_id_ending" to distinguish it from those.

So for Kenzo's situation you could use this:

    qc:
      seq_id_ending: "/[12]"

@louiejtaylor what do you think?  Is this the sort of thing you had in mind?

**Comment by louiejtaylor** [comment]
I've just realized that I never actually responded to this! This looks perfect, Jesse--I added a commit to the `old-illumina-seq-ids` branch which updates the docs with that new config option. Feel free to edit my description if you think anything is inaccurate, and then fire off a PR.

Thinking longer-term, my understanding is that the `sample_intake` rule checks for this param and if it doesn't exist, proceeds as usual--is that right? This is probably the right way to do it to maintain compatibility with all v2 config files, but for v3.0, should we include this as a default config option? (And maybe have the rule check to see whether there's a non-empty string before processing anything?)

**Comment by ressy** [comment]
That's right, since I used a call to `get` in `Cfg['qc'].get('seq_id_ending')` and then check if that has a value it'll just ignore all that by default... but that's not our usual pattern, where we really should have the default explicitly present in the config, so we can tidy that up for v3.0.  I'd make a pull request now but I saw that the latest test just failed (and I doubt it's due to your documentation update).  Knowing our usual luck it's probably some odd package dependency thing.  But in any case we can get that solved and added in on Tuesday.  Thanks!

**Comment by louiejtaylor** [comment]
It looks like what is failing is the docs, so I did break it somehow...I'm not really sure how to troubleshoot that though, because as far as I can tell all my changes are reflected in the current documentation (?)

Something to troubleshoot later

**Comment by louiejtaylor** [comment]
Oops, didn't mean to close!

**Comment by ressy** [comment]
Almost done here, but we needed to pull in recent changes from a hotfix for #224 into this branch too (that's why it sounded familiar!).  When those tests come back clean I'll make a pull request.
