### ISSUE TITLE
16S data

### ISSUE THREAD

**Issue by wangjiawen2013** [sunbeam-labs/sunbeam#228]
Dear,
Kraken 2 also provides support for databases not based on NCBI's taxonomy. Currently, these include the 16S databases: Greengenes, SILVA, and RDP. Can I use sunbeam to analyze 16S sequencing data ?

**Comment by louiejtaylor** [comment]
Thanks for the issue! I think the discussion in https://github.com/sunbeam-labs/sunbeam/issues/206 may be relevant here. 

The short answer is basically that, while you could probably run the pipeline without error, we don't recommend using it to analyze 16S data since we haven't designed or tested the pipeline for it.

Also, regarding your earlier question about kraken2, it will be the default classifier in the next major version of Sunbeam. In the meantime, we've written a Sunbeam extension, [sbx_kraken2](https://github.com/louiejtaylor/sbx_kraken2) ([further discussed here](https://github.com/sunbeam-labs/sunbeam/issues/208#issuecomment-514405606)), which allows for you to run kraken2 with the current version of Sunbeam.

**Comment by wangjiawen2013** [comment]
Kraken 2 also provides support for databases not based on NCBI's taxonomy. Currently, these include the 16S databases: Greengenes, SILVA, and RDP. It would be cool if sunbeam can process 16S data. So, would you take it into consideration in the next sunbeam version ?
