### ISSUE TITLE
multithreads

### ISSUE THREAD

**Issue by wangjiawen2013** [sunbeam-labs/sunbeam#230]
Dear,

I noticed that all the threads were set to 4 in sunbeam_config.yml by default (I changed 4 to 20 in the config file), but in fact the virtual thread is only 1 for all the process (eg. cutadapt, blastn, blastx). It seemed that "threads" in the config file didn't work. I know that snakemake needs the parameter -j to run multithreaded. Does sunbeam need to set the parameter -j to run multithreaded ?

**Comment by louiejtaylor** [comment]
Thanks for the issue! You are correct--by default Sunbeam (as it runs on snakemake) will only run on one core unless you give it more with `-j`/`--cores`. The thread numbers in the config file refer to the maximum number of cores that you allow that rule to use. For example, if you run sunbeam with the option `--cores 100` and each rule/processing step uses 20 threads, it will run 5 rules at once. 

We do mention that the Sunbeam command takes in any Snakemake options in the docs (https://sunbeam.readthedocs.io/en/latest/usage.html#running) but perhaps we should be more explicit about multithreading being something you have to pass, rather than using all available cores by default. Thoughts @ressy?

**Comment by ressy** [comment]
@louiejtaylor yeah, I think it'd make sense to mention it more prominently.  How about right in the intro to the Running section?  We could append a quick description to the existing list (`-n`, `-k`, `-p`).  I like your example (100 total / 20 per rule = 5 at once) -- that clarifies the per-rule and overall thread management concisely.

**Comment by louiejtaylor** [comment]
We added additional explanation to the docs for this. Thank you again for the issue!
