### ISSUE TITLE
rerun could not: detect non-existing output, notice a failed job and missed detecting an error from the log

### ISSUE THREAD

**Issue by aimirza** [sunbeam-labs/sunbeam#233]
After running megahit I noticed that the assembled reads for one sample failed to generate (not present). An error occurred when running "builder build." Despite these issues, Sunbeam failed to detect that the file was missing or that there was an error when rerunning `all_assembly ` with the flag `--rerun-incomplete`.  After attempting to rerun, Sunbeam says "there is nothing to be done." I had no issues rerunning any other step. I am using the stable version of Sunbeam, installed 2 weeks ago. Here is the log error:

```
b'megahit_sdbg_build: cx1_seq2sdbg.cpp:427: void cx1_seq2sdbg::read_seq_and_prepare(cx1_seq2sdbg::seq2sdbg_global_t&): Assertion `fscanf(contig_info, "%lld%lld", &num_contigs, &num_bases) == 2\' failed.'
Error occurs when running "builder build" for k = 29
```

**Comment by ressy** [comment]
@aimirza I think this case would be handled more clearly by the better megahit rules in #194, but that change isn't merged into a stable release just yet-- hoping for later this month.  (In the latest stable version it creates an empty contigs file for *any* error condition, but with the change from #194 it only does that when it actually didn't assemble any contigs.)  I think that's why Sunbeam didn't notice the problem.

But as for the actual error, I haven't seen that one from megahit myself.  The problems we've seen tend to usually be memory related, but this one is complaining about a problem parsing a .info file ([this line I think](https://github.com/voutcn/megahit/blob/b70d24b8d719af9161e5329005bc41111110dc18/cx1_seq2sdbg.cpp#L427)).  It expects to find exactly two items (number of contigs, number of bases) and fails because it found some other number.  If you remove your `sunbeam_output/assembly/{sample}-contigs.fa` and `sunbeam_output/assembly/megahit/{sample}/` for that one sample, and re-run all_assembly, does it fail at the same point?  If so, what do you see for that sample if you do
`cat sunbeam_output/assembly/megahit/{sample}/intermediate_contigs/*.info`?  It should show a bunch of pairs of integers, just going by how it behaves for a working case on my end.

**Comment by aimirza** [comment]
> If you remove your `sunbeam_output/assembly/{sample}-contigs.fa` and `sunbeam_output/assembly/megahit/{sample}/` for that one sample,

You meant `sunbeam_output/assembly/contigs/{sample}-contigs.fa` correct?

**Comment by ressy** [comment]
Whoops, yes, that's right for the first one.  Plus that whole intermediate megahit directory too.

**Comment by aimirza** [comment]
Deleting those files solved the problem and ran with no fails or errors :)
Thank you!

**Comment by ressy** [comment]
Odd!  But I'm glad it worked on the second try, anyway.  And for what it's worth the next release should at least handle the failure a bit more clearly if that does come up again at any point.
