### ISSUE TITLE
Pinned packages should be updated

### ISSUE THREAD

**Issue by ressy** [sunbeam-labs/sunbeam#248]
We have a handful of packages with pinned versions in the environment file that should get updated where possible (kraken is a major enough change from 1 to 2 that we'll handle that separately, though).

 * kraken=1.0: it's on 2 now but we'll handle this separately.  may still be worth incrementing to a minor higher version (there's a 1.1.1) to allow the snakemake upgrade below and ease the way for kraken 2.
 * snakemake=5.5.0: it's now at 5.8.1, and as of 5.7.0 it supports Path objects transparently for input/output entries in rules, so it would definitely be a nice to have.  The [other changes](https://snakemake.readthedocs.io/en/stable/project_info/history.html) are either bugfixes or changes that should not affect our use, I think.  I'm getting a conflict between this and kraken 1 around an indirect perl dependency so maybe this will wait until the kraken update.
 * jellyfish=1.1.11=1: I actually don't think we need this at all since the kraken package will pull in whatever jellyfish it needs as its own dependency.
 * trimmomatic=0.36: it's now at 0.39.  Were we pinned at 0.36 for any particular reason?  The 0.39 links point to the [0.32 manual](http://www.usadellab.org/cms/uploads/supplementary/Trimmomatic/TrimmomaticManual_V0.32.pdf) and Changelog stops at 0.30, so a check on our test output before/after might be the easiest test if anything changed here.

**Comment by ressy** [comment]
I've set `kraken<2` to allow version 1.1.1 (though the package name itself is different for 2 so that might be fine either way) and it looks like the newest Snakemake can now install alongside it, but now something failed during testing in test_extensions.   It says "Config file sbx_test not found" so it looks like the command-line arguments didn't get parsed as they should have when using the newer Snakemake.

**Comment by ressy** [comment]
Pulled in changes from dev including the kraken2 improvement from #254.  I expect there still may be some kind of argument parsing issue with the newer Snakemake, though.

**Comment by louiejtaylor** [comment]
I've figured out the issue with the new Snakemake version. This is the usage guide for the `--configfile` option in 5.5.0:

    --configfile FILE     Specify or overwrite the config file of the workflow
                        (see the docs). Values specified in JSON or YAML
                        format are available in the global config dictionary
                        inside the workflow.

And in 5.8.1:

      --configfile FILE [FILE ...], --configfiles FILE [FILE ...]
                        Specify or overwrite the config file of the workflow
                        (see the docs). Values specified in JSON or YAML
                        format are available in the global config dictionary
                        inside the workflow. Multiple files overwrite each
                        other in the given order.

New Snakemake can handle multiple config files. Which is kinda cool, but messes with the way we do things (e.g. trying to read the target rule name as a config filepath). I checked other Snakemake versions (5.7.0 can take multiple, 5.6.0 only takes one).

Seems like 5.6.0 would work fine. Updating to >=5.7.0 would require going in and editing a bunch of documentation/repos to warn users about this behavior. I could probably rewrite the tests to pass with 5.8.1 by shuffling the argument order of the `sunbeam run` calls, which is kinda lame.

Alternately, some logic could intercept the unparsed args to the `sunbeam run` call, pull out anything that looks like a rule name, and reshuffle the order of the args that are piped to snakemake. I kind of like this idea, but I'm not sure how much work it'd entail (meaning it would probably not get done soon).

Gonna leave this here for now and pin to snakemake 5.6.0, since all the tests pass.
 @ressy or @eclarke--if you don't mind, I'd appreciate your opinion/vote on what option you think would be best. No rush, though, as this is not urgent and you are both technically retired from this project :D

**Comment by ressy** [comment]
Thanks Louis!  I think that all makes sense-- if going to 5.7.0 is a major change, it's reasonable to defer that to a separate update from this issue+branch.  At least now we know what we're in for.  I'll still look forward to clearing out all those `str(...)` calls in the rules at some point but that's hardly an urgent change ;)

And thanks for pushing this along, too.  I keep hoping I'll have a chance to hop back in but it's been a continuous time crunch lately.

**Comment by ressy** [comment]
Oh and as far as these changes go, looks like we've covered snakemake, kraken, grabseqs, jellyfish (also h5py), so, maybe just trimmomatic left.  Does that sound right?

**Comment by louiejtaylor** [comment]
You are correct--testing trimmomatic now!

**Comment by ressy** [comment]
Nice!
