### ISSUE TITLE
running sbx_kraken2 from qc'd data

### ISSUE THREAD

**Issue by bcpd** [sunbeam-labs/sunbeam#250]
Hi all,

This seems like a simple-to-solve problem, but how can the kraken2 extension rules be modified so that the script runs from qc'd data, instead of from raw files?

Thanks!

**Comment by louiejtaylor** [comment]
Hi @bcpd, thanks for the issue!

The kraken2 extension should be using QC'd data. Looking at the relevant part (lines 1-3) of the kraken2 extension rules (https://github.com/louiejtaylor/sbx_kraken2/blob/master/sbx_kraken2.rules#L3), the input to the classify rule are the reads in the `decontam` folder:

    rule kraken2_classify_report:
        input:
            expand(str(QC_FP/'decontam'/'{{sample}}_{rp}.fastq.gz'),rp = Pairs)

Those reads have undergone QC, and been decontaminated (host reads removed; if you added a host genome).

Are you seeing this rule pulling from a different place? If so, do you mind pasting the rule output? Thank you!

**Comment by bcpd** [comment]
Thank you for such a quick reply. Sorry, I misspoke. The all_classify pipeline generates qc'd reads that are used by kraken for the classification step. Running "all_kraken2" after this pipeline repeats the qc-decontamination process, rather than start from the decontam folder. Should "sunbeam run --use-conda --configfile=sunbeam_config.yml kraken2_classify_report" be run to override the default behavior?

Many thanks.

**Comment by louiejtaylor** [comment]
No worries! And that's odd--if you've already completed QC, it shouldn't be trying to re-run it unless those files (specifically the ones in the `decontam` folder) no longer exist. Using `kraken2_classify_report` as the target rule will probably not work since there are wildcards in the rule inputs; you were right to run `all_kraken2` .

What I think the problem might be is that snakemake will rerun rules if a certain output file is older than input files. This usually doesn't happen, but I'm not really sure what snakemake counts as input files (e.g. does it consider a newly edited config a "new input"?). When this happens to me, sometimes you can catch snakemake/Sunbeam up by running with the `--touch` option. This essentially does a dry run and updates the timestamps of all the already existing output files to be in the order they'd be run, which has solved Sunbeam trying to re-run rules it had already completed for me in the past.

Try running:

    sunbeam run --touch --use-conda --configfile=sunbeam_config.yml all_kraken2

and then a dry-run (with `-n`) of your analysis:

    sunbeam run -n --use-conda --configfile=sunbeam_config.yml all_kraken2

to see if it's still trying to rerun all the QC steps.

**Comment by louiejtaylor** [comment]
Hi @bcpd, I'm going to close this issue for now since there hasn't been much activity on it for a bit. Please feel free to reopen it if you're still having problems!
