### ISSUE TITLE
Sunbeam segfaults at CLASSIFY step

### ISSUE THREAD

**Issue by Sabitaghimire17** [sunbeam-labs/sunbeam#267]
Ubuntu 16.04 LTS; Sunbeam v2.1.0

Attempting to run SUNBEAM using a pre-built KRAKEN database (http://ccb.jhu.edu/software/kraken/dl/minikraken_20171019_8GB.tgz).
 
Getting a segfault error:
[2020-01-30T160550.334043.snakemake.log](https://github.com/sunbeam-labs/sunbeam/files/4136288/2020-01-30T160550.334043.snakemake.log)
(We are removing the failed CLASSIFY folder as per recommendations; is there another folder somewhere else that we are failing to delete?)

Config File is attached.
[sunbeam_config.txt](https://github.com/sunbeam-labs/sunbeam/files/4136297/sunbeam_config.txt)

What are we missing?

**Comment by louiejtaylor** [comment]
Thanks for the issue! I've not seen this particular problem before, but have a few hypotheses.

1. How much total/available memory does your machine have? The 8GB minikraken database in theory needs 8GB free, but I generally try to have a bit extra available.
2. a. Did you install Sunbeam from the dev or stable branch? If dev, how recently?
    b. With the Sunbeam conda environment activated, do you mind pasting the output of this command: `conda list | grep kraken`?

**Comment by Sabitaghimire17** [comment]
Thank you for your prompt response. Here are the answers to your questions. 
1. 256 GB free

2. a. Stable branch
2. b. 
kraken                    1.0                  pl5.22.0_0    bioconda
kraken-biom               1.0.1                      py_2    bioconda

**Comment by louiejtaylor** [comment]
Welp, there go both of my hypotheses. Haha. Follow-up questions:

 - Do you have any other kraken databases you could test? If not, we can get you set up with a minimal one for testing to see whether this problem is specific to this particular minikraken database, or a general kraken problem.
 - Do the tests pass locally? You can test this by `cd`'ing to your directory where sunbeam is installed, then running:

```{bash}
bash tests/run_tests.bash
```
If that passes (or if you ran them on install and they passed), could you also run:

      bash tests/run_tests.bash -e sunbeam

To see whether there's an issue with your particular env.

**Comment by cement-head** [comment]
We ran the tests after install and everything came up without issues.

We are getting this error after we (initially) tried to use the 16S_SILVA db as a vanilla download not realising that it had to be reformatted in the KRAKEN format (kinda dumb in retrospect).

So...it might be because SUNBEAM barfed on a bad KRAKEN db and something is wonky on re-start.  We're doing a vanilla restart of the pipeline from the beginning and will let you know if it barfs at the same stage.

**Comment by Sabitaghimire17** [comment]
It barfed at the same stage again.

**Comment by louiejtaylor** [comment]
Alright, thanks. I'm going to try to reproduce the problem on Ubuntu 16.04 with the minikraken db you linked and will get back to you.

**Comment by Sabitaghimire17** [comment]
Okay, it worked with the smaller (4 GB) miniKRAKEN database, BUT the pipeline "finished" _without_ perfoming the CONTIG ANNOTATION, BLAST, and/or MAPPING.  Restarting the pipeline results in SUNBEAM stating that there is nothing to be done.

```
$ sunbeam run --cores 14 --configfile=sunbeam_config.yml --use-conda final_report
Running: snakemake --snakefile /home/bollman_lab/sunbeam-stable/Snakefile --cores 14 --configfile=sunbeam_config.yml --use-conda final_report
Found extension sbx_anvio in folder sbx_anvio
Found extension sbx_report in folder sbx_report
Collecting host/contaminant genomes... done.
Collecting target genomes... done.
Building DAG of jobs...
Nothing to be done.
```

Is this the expected behaviour?  Or...if I want the contig annotation, etc - should I run SUNBEAM without the report extension?

**Comment by louiejtaylor** [comment]
Glad you got kraken to run something! For what it's worth, the minikraken database you linked works fine in my hands on Ubunru 16.04.

When you pass Sunbeam a target rule (`final_report` in your example above), sunbeam will only perform the steps required to produce the rule you ask for. Since the only thing `final_report` needs is the kraken classifications, it did not run mapping/annotation. If you'd like to run them all in the same command, you can pass multiple target rules like so:

    sunbeam run --cores 14 --configfile=sunbeam_config.yml --use-conda final_report all_mapping all_annotate

(see [this docs page](https://sunbeam.readthedocs.io/en/latest/usage.html#running) for more info)
