### ISSUE TITLE
Snakemake wildcards

### ISSUE THREAD

**Issue by MichWeb75** [sunbeam-labs/sunbeam#268]
Hi, I am trying to understand what the `sample_intake` rule is doing but I really have problems to find out how the wildcards make sense here. Maybe you can help me?

1) How is the input statement working ? Where is the wildcards.sample , wildcards.rp is assigned ?
2) What is the Path statement doing ?
`Path(output[0]).symlink_to(input[0])`

```
rule sample_intake:
    input:
        lambda wildcards: Samples[wildcards.sample][wildcards.rp]
    output:
        str(QC_FP/'00_samples'/'{sample}_{rp}.fastq.gz')
    params:
        suffix = Cfg['qc'].get('seq_id_ending')
    run:
        if params.suffix:
            qc.strip_seq_id_suffix(input[0], output[0], params.suffix)
        else:
            Path(output[0]).symlink_to(input[0])
```

**Comment by ressy** [comment]
Ah yeah this one is using some of the weirder Snakemake features.  I'll try to go through it step by step.

When we give a function as input instead of a string (in his case a one-off lambda function, but it could have been the name of a function defined elsewhere), Snakemake passes an object containing all the wildcards to the function and expects to get back corresponding file path.  Here the output specifies that there's a "sample" wildcard and an "rp" wildcard to be parsed from the output filename, so it hands those to the input function, which just uses them as keys to the Samples dictionary and returns the corresponding sample path.

That Path statement just creates a symbolic link so that the output filename points back to the original input filename (essentially a do-nothing step but it lets the Snakemake rule see that sample_intake has been done).  That happens depending on `params.suffix`.

Snakemake goes backwards from output to input, so the whole process is like:

 1. Snakemake is asked to make a file, say, `qc/00_samples/somesample_1.fastq.gz`
 2. It sees that the sample_intake's output pattern `qc/00_samples/{sample}_{rp}.fastq.gz` matches, so it uses sample_intake and assigns `sample=somesample` and `rp=1`
 3. It calls the input function with those wildcards defined
 4. The input function gives the wildcards as keys to our global dictionary of Samples (first the sample name to get one dictionary, then the read pair identifier nested in that to get the filename) and returns the original path to the sample
 5. It calls the code in the run block, which decides if it needs to modify the sequence IDs depending on a configuration option we've stored in the rule parameters.  If so, it runs a function to write a modified version to the output file, but if not, it just symlinks the original file.

This feature was added recently (for #221) to handle certain sequence IDs for Illumina's old FASTQ style, but isn't needed in most cases, which is why there's the default do-nothing behavior if no `seq_id_ending` is defined.
