### ISSUE TITLE
bam file from all_coverage not compatible with other programs

### ISSUE THREAD

**Issue by aimirza** [sunbeam-labs/sunbeam#270]
Why is that when I try to run the `{sample}.sorted.bam` files (generated from the `all_coverage`) with other programs that use bam files it doesn't work? For example, when I try to calculate coverage stats using the script `jgi_summarize_bam_contig_depths` from MetaBat or `pileup.sh` from BBMap, the output is blank. I know that `all_coverage` generates a coverage file but the annotation software I want to use ([MetaErg](https://www.frontiersin.org/articles/10.3389/fgene.2019.00999/full)) requires the coverage format to be exactly like the output from `jgi_summarize_bam_contig_depths`.  

An example coverage file is here:
https://github.com/xiaoli-dong/metaerg/blob/master/example/demo.depth.txt

**Comment by louiejtaylor** [comment]
Hi @aimirza, thanks for the issue! I'll try to reproduce the problem--I've not had this issue using the .bam files in other programs, although I think I've only imported them into IGV. Are you getting any particular error, or just blank output?

**Comment by louiejtaylor** [comment]
Update: I can't reproduce the problem with BBMap version 38.76. My sunbeam installation is using samtools 0.1.19-96b5f2294a. For a toy example of a sample with a single read mapping to a single contig, BBMap produces the following output:

    #ID     Avg_fold        Length  Ref_GC  Covered_percent Covered_bases   Plus_reads      Minus_reads     Read_GC Median_fold     Std_Dev
    test_contig     0.0701  1996    0.0000  7.0140  140     2       0       0.4214  0       0.26

Which is correct, so far as I can tell--it matches the output generated by Sunbeam in the `contigs_coverage.txt` file:

    sample,contig,sum,min,max,mean,median,stddev,coverage,length
    testreads,test_contig,140,0,1,0.07014028056112225,0.0,0.25538328372062513,140,1996

Are there any differences in your situation--e.g. multiple contigs, or different software versions, that I should test?

Alternately, you could consider converting the data contained within `contigs_coverage.txt` into the format your downstream analysis requires. It looks to me like all the required information is present in the `contigs_coverage.txt` (although you can correct me if I'm wrong), you'd just need to wrangle it a bit with pandas/R/your favorite table-processing tool. This approach would likely be faster, as you'd just be re-formatting the output rather than processing the whole BAM again.

**Comment by aimirza** [comment]
Thank you for looking into it! No errors. I get blank data but the scripts seem to work. 
From both scripts, `jgi_summarize_bam_contig_depths` and `pileup.sh` I get a file with only headers and no data.

**Comment by aimirza** [comment]
I am using sunbeam v2.0.2. 
No problem, I will convert the data to the format I need. Thanks!

**Comment by aimirza** [comment]
Sorry, for some reason that sample I was testing, the smallest sample, did not assemble...
