### ISSUE TITLE
Any way to remove temporary files for all_decontam?

### ISSUE THREAD

**Issue by SimenHyllHansen** [sunbeam-labs/sunbeam#275]
When I run `sunbeam run -- --configfile project/sunbeam_config.yml --cores 4 all_decontam` everything works as it should, and I end up with my final files in the decontam-folder inside qc. However, other folder are made for each preceding step, effectively multiplying the storage space needed to get to the decontam-stage by 4 or 5 if I recall correctly. 

This will be a huge problem for me if I want to run all_decontam on my 8TB of data, as I will not have enough space for storing so much data. I therefore wonder if there is any way of automatically deleting the data that is inbetween 00_samples and decontam when each sample is passed into the decontam-stage? I found the option `--delete-temp-output`, but it does not seem to be what I am after, as I get no output at all when using that option.

**Comment by louiejtaylor** [comment]
Hi @SimenHyllHansen, thanks for the issue and sorry for the slow response! There's a target rule called `clean_qc` that should do what you're looking for, I think. You run it like:

    sunbeam run -- --configfile project/sunbeam_config.yml clean_qc

**Comment by SimenHyllHansen** [comment]
Thank you for your answer! This only seems to produce qc-files, but leaves out host-filtering (so I don't end up with the desired decontam-output). I tried with clean_decontam, but that option does not exist it seems.

**Comment by louiejtaylor** [comment]
(sorry for the terribly late reply!)

You are correct, it does not exist. Although, it seems like a useful thing to add--I've certainly done this cleanup process manually because it does take up a lot of space.

Pinging @ressy to sanity check me later today--we have a rule called `clean_qc` which requires as input the cleaned fastqs and deletes intermediate files:

    input:
        expand(
            str(QC_FP/'cleaned'/'{sample}_{rp}.fastq.gz'),
            sample=Samples.keys(), rp=Pairs)
    params:
        cutadapt_fp = str(QC_FP/'01_cutadapt'),
        trimmomatic_fp = str(QC_FP/'02_trimmomatic'),
        komplexity_fp = str(QC_FP/'03_komplexity')
    output:
        touch(".qc_cleaned")
    shell:
        """
        rm -r {params.cutadapt_fp} && \
        rm -r {params.trimmomatic_fp} && \
        rm -r {params.komplexity_fp}
        """

Should we have a similar one for decontam? If so, should it remove the cleaned reads? We could definitely clean up the host read ids `QC_FP/'decontam'/'intermediates'/'{sample}_hostreads.ids'`, at the very least

**Comment by Ulthran** [comment]
Hi all, coming back to this 3.5 years later, I've got a PR #408 that adds the desired clean_decontam target. I'm wondering though if it would be better to instead add a config option like `keep_intermediates` or something that will cause all targets that would get cleaned by `clean_decontam` to be temp(). That way the files we don't want to take up space will be removed asap instead of building them all up and then cleaning them at the end of the run.

**Comment by ressy** [comment]
Not that I've touched any Sunbeam code in a long long while, but for what it's worth, I think dynamically calling or not calling `temp()` on relevant outputs when defining the rules sounds like a fine idea.  If I remember right Snakemake will even try to structure the order of jobs to minimize the number of temp outputs sitting around, in addition to removing them as those jobs finish, so that could definitely be helpful for managing space.  And in the context of Sunbeam itself all this makes sense to me (though again, I haven't done any metagenomic stuff in a long while).

Louis, I'm sorry if we never talked about this back in 2021 when you mentioned me here-- I can't remember at this point :)

**Comment by Ulthran** [comment]
From the responses I've gotten asking users about this, it sounds like this won't be a very heavily used feature either way it's implemented. I'll merge the PR to add the `clean_decontam` rule for symmetry with `clean_qc` and to avoid adding more options to the config.
