### ISSUE TITLE
Memory usage does not clear after run

### ISSUE THREAD

**Issue by bcpd** [sunbeam-labs/sunbeam#276]
Hi all,

I'm not sure whether to frame this as a sunbeam-specific issue, but I've noticed that the computer's memory use does not clear after sunbeam runs are complete (e.g. if 40GB are used, the number stays the same). What I typically run is

sunbeam run --configfile=sunbeam_config.yml all_classify -k -p --cores 6

Additional details below:

sunbeam version: sunbeam v2.1.1+dev79.gc24f00f

conda info -e:
sunbeam                  /home/pedro/miniconda3/envs/sunbeam
sunbeam-tmp.GqGrtuMvxR     /home/pedro/miniconda3/envs/sunbeam-tmp.GqGrtuMvxR
                         /naboo/storage/runs/P00C3/sunbeam_output/.snakemake/conda/0c9a1945
                         /naboo/storage/runs/p00bg2/sunbeam_output/.snakemake/conda/88301c0e

**Comment by louiejtaylor** [comment]
My bet is that this setting would be accessible via kraken or something on your machine. We definitely don't handle memory management within Sunbeam. I want to ask a bit more to see how much of a problem this is for you.

I am not 100% sure how this works, as I'm not a computer scientist by training (so please correct me if you know better). My understanding of how memory management works is that information (e.g. your kraken db) that has been read into memory, but is no longer in use, is not necessarily cleared right away by the system. I think this is for efficiency's sake--it's probably more efficient to keep things around in case you need them again rather than clearing it right away from the system's perspective. However, if something else needs that memory, things that are no longer in use _should_ be cleared.

Are you finding that this 40GB of memory is still used if you run a process afterwards that would require some of that memory? For example, if your machine has 50GB RAM, 40GB is "in use" after your Sunbeam run--then running a process that uses, say, 30GB should result in that 40GB being freed. If not, than that's a problem.

If it is able to be freed if another process needs it, but you'd still like to kick it out of memory when you're done with it (e.g. your HPC charges you for RAM usage), I'd recommend a utility like [vmtouch](https://hoytech.com/vmtouch/). We've used it to play with making kraken databases persistent (or not) in RAM and it's very easy to use.

**Comment by bcpd** [comment]
Thank you for the prompt reply. I am not sure, but it looks like memory is not freed after running a process. But please feel free to close this issue.
