### ISSUE TITLE
Testing error after installation

### ISSUE THREAD

**Issue by seonyeong00** [sunbeam-labs/sunbeam#284]
Dear developers of the Sunbeam, 

This is Seonyeong from South Korea. 
After installing Sunbeam into our linux server, in order to check if our installation is done correctly,  we ran ./install.sh. 
However, we have an issue in the test_mapping, which automatically resulted in test failed.  

In this case, what can we do for this "failed" error?  
See the attached file to see what's going on with our error. 
Thank you so much for your support, 
Seonyeong.  
<img width="515" alt="a1" src="https://user-images.githubusercontent.com/70444335/95149151-3210a900-07c0-11eb-80af-51cf5a1c5f6e.PNG">
<img width="389" alt="a2" src="https://user-images.githubusercontent.com/70444335/95149162-36d55d00-07c0-11eb-8f38-c0a70261300d.PNG">

**Comment by adefewings** [comment]
Seeing the same issue here.  Not sure if there is anything actually wrong, but happy to provide any info to help resolve.

**Comment by ressy** [comment]
@seonyeong00 @adefewings sorry for the delayed response on this.  I think this is the result of an outdated test in the test suite and should be fixed in the latest development version.  Could you try using that (you should be able to `git checkout dev && git pull` from your existing sunbeam directory) and let us know how it goes?

**Comment by Ulthran** [comment]
Assuming this is fixed, if not please open a new issue.
