### ISSUE TITLE
Installation failure "error while loading shared libraries: libmkl_rt.so"

### ISSUE THREAD

**Issue by cednotsed** [sunbeam-labs/sunbeam#293]
Hi all,

Just wanted to share an issue I faced during installation and one of the workarounds I used to deal with it. 
I encountered this error after installation and during testing:

```
rule remove_low_complexity:
    input: /tmp/tmp.5milCHBScI/sunbeam_output/qc/02_trimmomatic/dummyecoli_1.fastq.gz, /tmp/tmp.5milCHBScI/sunbeam_output/qc/log/komplexity/dummyecoli.filtered_ids
    output: /tmp/tmp.5milCHBScI/sunbeam_output/qc/03_komplexity/dummyecoli_1.fastq.gz
    jobid: 41
    wildcards: sample=dummyecoli, rp=1


        gzip -dc /tmp/tmp.5milCHBScI/sunbeam_output/qc/02_trimmomatic/dummyecoli_1.fastq.gz | rbt fastq-filter /tmp/tmp.5milCHBScI/sunbeam_output/qc/log/komplexity/dummyecoli.filtered_ids |        gzip > /tmp/tmp.5milCHBScI/sunbeam_output/qc/03_komplexity/dummyecoli_1.fastq.gz

rbt: error while loading shared libraries: libmkl_rt.so: cannot open shared object file: No such file or directory
[Mon Apr  5 10:06:03 2021]
Error in rule remove_low_complexity:
    jobid: 41
    output: /tmp/tmp.5milCHBScI/sunbeam_output/qc/03_komplexity/dummyecoli_1.fastq.gz
    shell:

        gzip -dc /tmp/tmp.5milCHBScI/sunbeam_output/qc/02_trimmomatic/dummyecoli_1.fastq.gz | rbt fastq-filter /tmp/tmp.5milCHBScI/sunbeam_output/qc/log/komplexity/dummyecoli.filtered_ids |        gzip > /tmp/tmp.5milCHBScI/sunbeam_output/qc/03_komplexity/dummyecoli_1.fastq.gz

        (exited with non-zero exit code)

Removing output files of failed job remove_low_complexity since they might be corrupted:
/tmp/tmp.5milCHBScI/sunbeam_output/qc/03_komplexity/dummyecoli_1.fastq.gz
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/users/astar/gis/tancsc/tools/sunbeam/.snakemake/log/2021-04-05T100522.067952.snakemake.log
x (log: /tmp/tmp.5milCHBScI/test_all.[out/err])
-- TESTS FAILED --
```

Seems like the Mkl dependency was not included in the installation and so I had to manually install the dependency using:
'conda install -c intel mkl'. This fixed everything for me.

Hope this is useful for someone else.

**Comment by louiejtaylor** [comment]
Hi @cednotsed, thanks for the issue! This seems to be very similar to a recent issue (#286), where a broken rust-bio-tools build was sporadically missing a dependency (blis in that case).

ressy tracked the issue down to a dichotomy between two different rust-bio-tools builds (detailed debugging in this bioconda issue: https://github.com/bioconda/bioconda-recipes/issues/27424). Interestingly, in the case he ran into where blis was missing, an mkl build was installed, so I wonder if you've found the complementary issue here.

The way we solved that problem was to temporarily add blis to the Sunbeam dependencies until a [patch to the rust-bio-tools conda recipe](https://github.com/bioconda/bioconda-recipes/pull/27752) goes through. I think a similar fix would be appropriate here. I'll leave this open for now but add in a patch on our end, and check about making the mkl dependency explicit in rbt.

Thanks again!

**Comment by ressy** [comment]
Thanks @louiejtaylor.  I ran into this too and I'm particularly confused by this blis-vs-mkl thing.  I opened a second issue at bioconda for this:

https://github.com/bioconda/bioconda-recipes/issues/27826

Whatever the reason that the mkl library is now needed, it *does* look installing the package makes it work, like @cednotsed said.  There's also an mkl package in conda-forge that worked for me.
